-- Orders: coordination records, not fulfillment records. Belong to syndicates.
-- Opened/closed/executed exclusively by the syndicate's one admin (syndicates.admin_user_id),
-- so no separate actor column is stored per action -- it would be redundant.
CREATE TYPE order_status AS ENUM ('open', 'closed', 'executed');

CREATE TABLE orders (
    order_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    syndicate_id  INTEGER NOT NULL REFERENCES syndicates(syndicate_id),
    status        order_status NOT NULL DEFAULT 'open',
    opened_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    deadline_at   TIMESTAMPTZ NOT NULL,
    closed_at     TIMESTAMPTZ,
    executed_at   TIMESTAMPTZ,
    CHECK (deadline_at > opened_at),
    CHECK (executed_at IS NULL OR closed_at IS NULL OR executed_at >= closed_at)
);

-- FK, looked up via "syndicate's orders" -- not auto-indexed by Postgres.
CREATE INDEX idx_orders_syndicate_id ON orders (syndicate_id);

-- Trigger: orders.status can only move forward (open -> closed -> executed)
CREATE OR REPLACE FUNCTION check_order_status_transition() RETURNS TRIGGER AS $$
BEGIN
  IF OLD.status = 'open' AND NEW.status NOT IN ('open', 'closed') THEN
    RAISE EXCEPTION 'orders can only move from open to closed';
  ELSIF OLD.status = 'closed' AND NEW.status NOT IN ('closed', 'executed') THEN
    RAISE EXCEPTION 'orders can only move from closed to executed';
  ELSIF OLD.status = 'executed' AND NEW.status != 'executed' THEN
    RAISE EXCEPTION 'executed orders cannot change status';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public, pg_temp;

CREATE TRIGGER trg_order_status_transition
BEFORE UPDATE OF status ON orders
FOR EACH ROW EXECUTE FUNCTION check_order_status_transition();

CREATE TABLE order_items (
    order_item_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id          INTEGER NOT NULL REFERENCES orders(order_id),
    product_id        INTEGER NOT NULL REFERENCES products(product_id),
    quantity          INTEGER NOT NULL DEFAULT 0,
    unit_price        INTEGER NOT NULL CHECK (unit_price > 0),
    max_quantity      INTEGER CHECK (max_quantity IS NULL OR max_quantity > 0),
    -- tiered items only; NULL = uncapped. Threshold items are capped via threshold_qty instead.
    CHECK (quantity >= 0),
    CHECK (max_quantity IS NULL OR quantity <= max_quantity)
    -- quantity is trigger-maintained from order_item_stakes -- see next migration
    -- unit_price: fixed at creation for threshold_bundle; live for tiered
);

-- FKs, joined constantly (check_stake_capacity, apply_smallest_remainder_apportionment,
-- order_item_resolution) -- not auto-indexed by Postgres.
CREATE INDEX idx_order_items_order_id ON order_items (order_id);
CREATE INDEX idx_order_items_product_id ON order_items (product_id);
