-- Products: external items being pooled for. This platform holds no inventory.
CREATE TYPE product_pricing_type AS ENUM ('threshold_bundle', 'tiered');

CREATE TABLE products (
    product_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT NOT NULL,
    description   TEXT,
    pricing_type  product_pricing_type NOT NULL,
    created_at    TIMESTAMPTZ DEFAULT now()
);

-- threshold_bundle products only
CREATE TABLE product_bundle_thresholds (
    product_id          INTEGER PRIMARY KEY REFERENCES products(product_id),
    threshold_qty       INTEGER NOT NULL CHECK (threshold_qty > 0),
    bundle_price        INTEGER NOT NULL CHECK (bundle_price > 0)
    -- per-unit price (cents) = bundle_price / threshold_qty
);

-- tiered products only: one row per price break. (0, 2499), (5, 2150), (10, 1800)
-- means 2499/unit from qty 0, 2150 from qty 5, 1800 from qty 10 and up.
CREATE TABLE product_price_tiers (
    product_id    INTEGER NOT NULL REFERENCES products(product_id),
    qty_floor  INTEGER NOT NULL CHECK (qty_floor >= 0),
    unit_price    INTEGER NOT NULL CHECK (unit_price > 0),
    PRIMARY KEY (product_id, qty_floor)
);
