-- Syndicates & membership.
-- No local users table -- wired directly to Supabase auth.users (id UUID PK).

CREATE TABLE syndicates (
    syndicate_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           TEXT NOT NULL,
    admin_user_id  UUID NOT NULL REFERENCES auth.users(id)
    -- admin_user_id should also be a syndicate_members row for this syndicate,
    -- but no trigger/RLS enforces it yet -- see "Open questions" in backend.md
);

CREATE TABLE syndicate_members (
    syndicate_id  INTEGER NOT NULL REFERENCES syndicates(syndicate_id),
    user_id       UUID NOT NULL REFERENCES auth.users(id),
    joined_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (syndicate_id, user_id)
);

-- FK indices
CREATE INDEX idx_syndicates_admin_user_id ON syndicates (admin_user_id);
CREATE INDEX idx_syndicate_members_user_id ON syndicate_members (user_id);

